### PR TITLE
Updated the readme.md

### PR DESCRIPTION
**Pull request by CoderSaty**
I have added all your social profiles and skills in order to improve your profile.

### CODE REVIEW

**Comment by nikhilshukla07** [comment]
Thankyou so mush for updating my repository :)

**Comment by nikhilshukla07** [comment]
Thankyou so much for updating my repository :)

**Comment by CoderSaty** [comment]
Hi If you think my changes were helpful consider adding a hacktoberfest-accepted label to my pull request.

**Comment by nikhilshukla07** [comment]
Ok

**Comment by nikhilshukla07** [comment]
done @CoderSaty

**Pull request merged**
